// @generated by roam-codegen
// DO NOT EDIT - regenerate with `cargo xtask codegen --swift`

import Foundation
import RoamRuntime

// MARK: - Vfs Method IDs

public enum VfsMethodId {
    public static let lookup: UInt64 = 0xac1f4b76a434caf5
    public static let getAttributes: UInt64 = 0xc968b68989c3f020
    public static let readDir: UInt64 = 0x075923273ab49e29
    public static let read: UInt64 = 0x9c80fd555999d0e1
    public static let write: UInt64 = 0x5d398e81123c3597
    public static let create: UInt64 = 0x2caaf8adf5eda0e1
    public static let delete: UInt64 = 0xfa37cb27061e7e2a
    public static let rename: UInt64 = 0x4d68b4b3208a8c07
    public static let setAttributes: UInt64 = 0x5dcd5793362fcd20
    public static let ping: UInt64 = 0xe35cdfdca59ce5ab
}

// MARK: - Vfs Types

public enum ItemType: Codable, Sendable {
    case file
    case directory
    case symlink
}

public struct LookupResult: Codable, Sendable {
    public var itemId: UInt64
    public var itemType: ItemType
    public var error: Int32

    public init(itemId: UInt64, itemType: ItemType, error: Int32) {
        self.itemId = itemId
        self.itemType = itemType
        self.error = error
    }
}

public struct ItemAttributes: Codable, Sendable {
    public var itemId: UInt64
    public var itemType: ItemType
    public var size: UInt64
    public var modifiedTime: UInt64
    public var createdTime: UInt64
    public var mode: UInt32

    public init(itemId: UInt64, itemType: ItemType, size: UInt64, modifiedTime: UInt64, createdTime: UInt64, mode: UInt32) {
        self.itemId = itemId
        self.itemType = itemType
        self.size = size
        self.modifiedTime = modifiedTime
        self.createdTime = createdTime
        self.mode = mode
    }
}

public struct GetAttributesResult: Codable, Sendable {
    public var attrs: ItemAttributes
    public var error: Int32

    public init(attrs: ItemAttributes, error: Int32) {
        self.attrs = attrs
        self.error = error
    }
}

public struct DirEntry: Codable, Sendable {
    public var name: String
    public var itemId: UInt64
    public var itemType: ItemType

    public init(name: String, itemId: UInt64, itemType: ItemType) {
        self.name = name
        self.itemId = itemId
        self.itemType = itemType
    }
}

public struct ReadDirResult: Codable, Sendable {
    public var entries: [DirEntry]
    public var nextCursor: UInt64
    public var error: Int32

    public init(entries: [DirEntry], nextCursor: UInt64, error: Int32) {
        self.entries = entries
        self.nextCursor = nextCursor
        self.error = error
    }
}

public struct ReadResult: Codable, Sendable {
    public var data: Data
    public var error: Int32

    public init(data: Data, error: Int32) {
        self.data = data
        self.error = error
    }
}

public struct WriteResult: Codable, Sendable {
    public var bytesWritten: UInt64
    public var error: Int32

    public init(bytesWritten: UInt64, error: Int32) {
        self.bytesWritten = bytesWritten
        self.error = error
    }
}

public struct CreateResult: Codable, Sendable {
    public var itemId: UInt64
    public var error: Int32

    public init(itemId: UInt64, error: Int32) {
        self.itemId = itemId
        self.error = error
    }
}

public struct VfsResult: Codable, Sendable {
    public var error: Int32

    public init(error: Int32) {
        self.error = error
    }
}

public struct SetAttributesParams: Codable, Sendable {
    public var mode: UInt32?
    public var modifiedTime: UInt64?

    public init(mode: UInt32?, modifiedTime: UInt64?) {
        self.mode = mode
        self.modifiedTime = modifiedTime
    }
}

// MARK: - Vfs Client

///  The VFS service trait - defines the RPC interface between client and server.
public protocol VfsCaller {
    ///  Look up an item by name in a parent directory.
    func lookup(parentId: UInt64, name: String) async throws -> LookupResult
    ///  Get attributes for an item.
    func getAttributes(itemId: UInt64) async throws -> GetAttributesResult
    ///  Read directory contents.
    ///  Use cursor=0 for first page, then use returned next_cursor for subsequent pages.
    func readDir(itemId: UInt64, cursor: UInt64) async throws -> ReadDirResult
    ///  Read file contents.
    func read(itemId: UInt64, offset: UInt64, len: UInt64) async throws -> ReadResult
    ///  Write file contents.
    func write(itemId: UInt64, offset: UInt64, data: Data) async throws -> WriteResult
    ///  Create a new file or directory.
    func create(parentId: UInt64, name: String, itemType: ItemType) async throws -> CreateResult
    ///  Delete an item.
    func delete(itemId: UInt64) async throws -> VfsResult
    ///  Rename/move an item.
    func rename(itemId: UInt64, newParentId: UInt64, newName: String) async throws -> VfsResult
    ///  Set attributes (permissions, times, etc.) on an item.
    func setAttributes(itemId: UInt64, params: SetAttributesParams) async throws -> VfsResult
    ///  Ping for connectivity check.
    func ping() async throws -> String
}

public final class VfsClient: VfsCaller {
    private let connection: RoamConnection

    public init(connection: RoamConnection) {
        self.connection = connection
    }

    public func lookup(parentId: UInt64, name: String) async throws -> LookupResult {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeVarint(parentId)
        payloadBytes += encodeString(name)
        let payload = Data(payloadBytes)
        let response = try await connection.call(methodId: 0xac1f4b76a434caf5, payload: payload)
        var cursor = 0
        try decodeRpcResult(from: response, offset: &cursor)
        let _result_itemId = try decodeVarint(from: response, offset: &cursor)
        let __result_itemType_disc = try decodeU8(from: response, offset: &cursor)
        let _result_itemType: ItemType
        switch __result_itemType_disc {
        case 0:
            _result_itemType = .file
        case 1:
            _result_itemType = .directory
        case 2:
            _result_itemType = .symlink
        default:
            throw RoamError.decodeError("unknown enum variant")
        }
        let _result_error = try decodeI32(from: response, offset: &cursor)
        let result = LookupResult(itemId: _result_itemId, itemType: _result_itemType, error: _result_error)
        return result
    }

    public func getAttributes(itemId: UInt64) async throws -> GetAttributesResult {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeVarint(itemId)
        let payload = Data(payloadBytes)
        let response = try await connection.call(methodId: 0xc968b68989c3f020, payload: payload)
        var cursor = 0
        try decodeRpcResult(from: response, offset: &cursor)
        let __result_attrs_itemId = try decodeVarint(from: response, offset: &cursor)
        let ___result_attrs_itemType_disc = try decodeU8(from: response, offset: &cursor)
        let __result_attrs_itemType: ItemType
        switch ___result_attrs_itemType_disc {
        case 0:
            __result_attrs_itemType = .file
        case 1:
            __result_attrs_itemType = .directory
        case 2:
            __result_attrs_itemType = .symlink
        default:
            throw RoamError.decodeError("unknown enum variant")
        }
        let __result_attrs_size = try decodeVarint(from: response, offset: &cursor)
        let __result_attrs_modifiedTime = try decodeVarint(from: response, offset: &cursor)
        let __result_attrs_createdTime = try decodeVarint(from: response, offset: &cursor)
        let __result_attrs_mode = try decodeU32(from: response, offset: &cursor)
        let _result_attrs = ItemAttributes(itemId: __result_attrs_itemId, itemType: __result_attrs_itemType, size: __result_attrs_size, modifiedTime: __result_attrs_modifiedTime, createdTime: __result_attrs_createdTime, mode: __result_attrs_mode)
        let _result_error = try decodeI32(from: response, offset: &cursor)
        let result = GetAttributesResult(attrs: _result_attrs, error: _result_error)
        return result
    }

    public func readDir(itemId: UInt64, cursor: UInt64) async throws -> ReadDirResult {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeVarint(itemId)
        payloadBytes += encodeVarint(cursor)
        let payload = Data(payloadBytes)
        let response = try await connection.call(methodId: 0x075923273ab49e29, payload: payload)
        var cursor_ = 0
        try decodeRpcResult(from: response, offset: &cursor_)
        let _result_entries = try decodeVec(from: response, offset: &cursor_, decoder: { data, off in
            let _name = try decodeString(from: data, offset: &off)
            let _itemId = try decodeVarint(from: data, offset: &off)
            let _itemType = try ({ data, off in
            let disc = try decodeU8(from: data, offset: &off)
            let result: ItemType
            switch disc {
            case 0:
                result = .file
            case 1:
                result = .directory
            case 2:
                result = .symlink
            default:
                throw RoamError.decodeError("unknown enum variant")
            }
            return result
        })(data, &off)
            return DirEntry(name: _name, itemId: _itemId, itemType: _itemType)
        })
        let _result_nextCursor = try decodeVarint(from: response, offset: &cursor_)
        let _result_error = try decodeI32(from: response, offset: &cursor_)
        let result = ReadDirResult(entries: _result_entries, nextCursor: _result_nextCursor, error: _result_error)
        return result
    }

    public func read(itemId: UInt64, offset: UInt64, len: UInt64) async throws -> ReadResult {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeVarint(itemId)
        payloadBytes += encodeVarint(offset)
        payloadBytes += encodeVarint(len)
        let payload = Data(payloadBytes)
        let response = try await connection.call(methodId: 0x9c80fd555999d0e1, payload: payload)
        var cursor = 0
        try decodeRpcResult(from: response, offset: &cursor)
        let _result_data = try decodeBytes(from: response, offset: &cursor)
        let _result_error = try decodeI32(from: response, offset: &cursor)
        let result = ReadResult(data: _result_data, error: _result_error)
        return result
    }

    public func write(itemId: UInt64, offset: UInt64, data: Data) async throws -> WriteResult {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeVarint(itemId)
        payloadBytes += encodeVarint(offset)
        payloadBytes += encodeBytes(Array(data))
        let payload = Data(payloadBytes)
        let response = try await connection.call(methodId: 0x5d398e81123c3597, payload: payload)
        var cursor = 0
        try decodeRpcResult(from: response, offset: &cursor)
        let _result_bytesWritten = try decodeVarint(from: response, offset: &cursor)
        let _result_error = try decodeI32(from: response, offset: &cursor)
        let result = WriteResult(bytesWritten: _result_bytesWritten, error: _result_error)
        return result
    }

    public func create(parentId: UInt64, name: String, itemType: ItemType) async throws -> CreateResult {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeVarint(parentId)
        payloadBytes += encodeString(name)
        payloadBytes += { v in
    switch v {
    case .file:
        return [UInt8(0)]
    case .directory:
        return [UInt8(1)]
    case .symlink:
        return [UInt8(2)]
    }
}(itemType)
        let payload = Data(payloadBytes)
        let response = try await connection.call(methodId: 0x2caaf8adf5eda0e1, payload: payload)
        var cursor = 0
        try decodeRpcResult(from: response, offset: &cursor)
        let _result_itemId = try decodeVarint(from: response, offset: &cursor)
        let _result_error = try decodeI32(from: response, offset: &cursor)
        let result = CreateResult(itemId: _result_itemId, error: _result_error)
        return result
    }

    public func delete(itemId: UInt64) async throws -> VfsResult {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeVarint(itemId)
        let payload = Data(payloadBytes)
        let response = try await connection.call(methodId: 0xfa37cb27061e7e2a, payload: payload)
        var cursor = 0
        try decodeRpcResult(from: response, offset: &cursor)
        let _result_error = try decodeI32(from: response, offset: &cursor)
        let result = VfsResult(error: _result_error)
        return result
    }

    public func rename(itemId: UInt64, newParentId: UInt64, newName: String) async throws -> VfsResult {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeVarint(itemId)
        payloadBytes += encodeVarint(newParentId)
        payloadBytes += encodeString(newName)
        let payload = Data(payloadBytes)
        let response = try await connection.call(methodId: 0x4d68b4b3208a8c07, payload: payload)
        var cursor = 0
        try decodeRpcResult(from: response, offset: &cursor)
        let _result_error = try decodeI32(from: response, offset: &cursor)
        let result = VfsResult(error: _result_error)
        return result
    }

    public func setAttributes(itemId: UInt64, params: SetAttributesParams) async throws -> VfsResult {
        var payloadBytes: [UInt8] = []
        payloadBytes += encodeVarint(itemId)
        payloadBytes += encodeOption(params.mode, encoder: { encodeU32($0) }) + encodeOption(params.modifiedTime, encoder: { encodeVarint($0) })
        let payload = Data(payloadBytes)
        let response = try await connection.call(methodId: 0x5dcd5793362fcd20, payload: payload)
        var cursor = 0
        try decodeRpcResult(from: response, offset: &cursor)
        let _result_error = try decodeI32(from: response, offset: &cursor)
        let result = VfsResult(error: _result_error)
        return result
    }

    public func ping() async throws -> String {
        let payload = Data()
        let response = try await connection.call(methodId: 0xe35cdfdca59ce5ab, payload: payload)
        var cursor = 0
        try decodeRpcResult(from: response, offset: &cursor)
        let result = try decodeString(from: response, offset: &cursor)
        return result
    }
}

// MARK: - Vfs Server

///  The VFS service trait - defines the RPC interface between client and server.
public protocol VfsHandler {
    ///  Look up an item by name in a parent directory.
    func lookup(parentId: UInt64, name: String) async throws -> LookupResult
    ///  Get attributes for an item.
    func getAttributes(itemId: UInt64) async throws -> GetAttributesResult
    ///  Read directory contents.
    ///  Use cursor=0 for first page, then use returned next_cursor for subsequent pages.
    func readDir(itemId: UInt64, cursor: UInt64) async throws -> ReadDirResult
    ///  Read file contents.
    func read(itemId: UInt64, offset: UInt64, len: UInt64) async throws -> ReadResult
    ///  Write file contents.
    func write(itemId: UInt64, offset: UInt64, data: Data) async throws -> WriteResult
    ///  Create a new file or directory.
    func create(parentId: UInt64, name: String, itemType: ItemType) async throws -> CreateResult
    ///  Delete an item.
    func delete(itemId: UInt64) async throws -> VfsResult
    ///  Rename/move an item.
    func rename(itemId: UInt64, newParentId: UInt64, newName: String) async throws -> VfsResult
    ///  Set attributes (permissions, times, etc.) on an item.
    func setAttributes(itemId: UInt64, params: SetAttributesParams) async throws -> VfsResult
    ///  Ping for connectivity check.
    func ping() async throws -> String
}

public final class VfsDispatcher {
    private let handler: VfsHandler

    public init(handler: VfsHandler) {
        self.handler = handler
    }

    public func dispatch(methodId: UInt64, payload: Data) async throws -> Data {
        switch methodId {
        case 0xac1f4b76a434caf5:
            return try await dispatchlookup(payload: payload)
        case 0xc968b68989c3f020:
            return try await dispatchgetAttributes(payload: payload)
        case 0x075923273ab49e29:
            return try await dispatchreadDir(payload: payload)
        case 0x9c80fd555999d0e1:
            return try await dispatchread(payload: payload)
        case 0x5d398e81123c3597:
            return try await dispatchwrite(payload: payload)
        case 0x2caaf8adf5eda0e1:
            return try await dispatchcreate(payload: payload)
        case 0xfa37cb27061e7e2a:
            return try await dispatchdelete(payload: payload)
        case 0x4d68b4b3208a8c07:
            return try await dispatchrename(payload: payload)
        case 0x5dcd5793362fcd20:
            return try await dispatchsetAttributes(payload: payload)
        case 0xe35cdfdca59ce5ab:
            return try await dispatchping(payload: payload)
        default:
            throw RoamError.unknownMethod
        }
    }

    private func dispatchlookup(payload: Data) async throws -> Data {
        var cursor = 0
        let parentId = try decodeVarint(from: payload, offset: &cursor)
        let name = try decodeString(from: payload, offset: &cursor)
        let result = try await handler.lookup(parentId: parentId, name: name)
        return Data(encodeResultOk(result, encoder: { encodeVarint($0.itemId) + { v in
    switch v {
    case .file:
        return [UInt8(0)]
    case .directory:
        return [UInt8(1)]
    case .symlink:
        return [UInt8(2)]
    }
}($0.itemType) + encodeI32($0.error) }))
    }

    private func dispatchgetAttributes(payload: Data) async throws -> Data {
        var cursor = 0
        let itemId = try decodeVarint(from: payload, offset: &cursor)
        let result = try await handler.getAttributes(itemId: itemId)
        return Data(encodeResultOk(result, encoder: { encodeVarint($0.attrs.itemId) + { v in
    switch v {
    case .file:
        return [UInt8(0)]
    case .directory:
        return [UInt8(1)]
    case .symlink:
        return [UInt8(2)]
    }
}($0.attrs.itemType) + encodeVarint($0.attrs.size) + encodeVarint($0.attrs.modifiedTime) + encodeVarint($0.attrs.createdTime) + encodeU32($0.attrs.mode) + encodeI32($0.error) }))
    }

    private func dispatchreadDir(payload: Data) async throws -> Data {
        var cursor_ = 0
        let itemId = try decodeVarint(from: payload, offset: &cursor_)
        let cursor = try decodeVarint(from: payload, offset: &cursor_)
        let result = try await handler.readDir(itemId: itemId, cursor: cursor)
        return Data(encodeResultOk(result, encoder: { encodeVec($0.entries, encoder: { encodeString($0.name) + encodeVarint($0.itemId) + { v in
    switch v {
    case .file:
        return [UInt8(0)]
    case .directory:
        return [UInt8(1)]
    case .symlink:
        return [UInt8(2)]
    }
}($0.itemType) }) + encodeVarint($0.nextCursor) + encodeI32($0.error) }))
    }

    private func dispatchread(payload: Data) async throws -> Data {
        var cursor = 0
        let itemId = try decodeVarint(from: payload, offset: &cursor)
        let offset = try decodeVarint(from: payload, offset: &cursor)
        let len = try decodeVarint(from: payload, offset: &cursor)
        let result = try await handler.read(itemId: itemId, offset: offset, len: len)
        return Data(encodeResultOk(result, encoder: { encodeBytes(Array($0.data)) + encodeI32($0.error) }))
    }

    private func dispatchwrite(payload: Data) async throws -> Data {
        var cursor = 0
        let itemId = try decodeVarint(from: payload, offset: &cursor)
        let offset = try decodeVarint(from: payload, offset: &cursor)
        let data = try decodeBytes(from: payload, offset: &cursor)
        let result = try await handler.write(itemId: itemId, offset: offset, data: data)
        return Data(encodeResultOk(result, encoder: { encodeVarint($0.bytesWritten) + encodeI32($0.error) }))
    }

    private func dispatchcreate(payload: Data) async throws -> Data {
        var cursor = 0
        let parentId = try decodeVarint(from: payload, offset: &cursor)
        let name = try decodeString(from: payload, offset: &cursor)
        let _itemType_disc = try decodeU8(from: payload, offset: &cursor)
        let itemType: ItemType
        switch _itemType_disc {
        case 0:
            itemType = .file
        case 1:
            itemType = .directory
        case 2:
            itemType = .symlink
        default:
            throw RoamError.decodeError("unknown enum variant")
        }
        let result = try await handler.create(parentId: parentId, name: name, itemType: itemType)
        return Data(encodeResultOk(result, encoder: { encodeVarint($0.itemId) + encodeI32($0.error) }))
    }

    private func dispatchdelete(payload: Data) async throws -> Data {
        var cursor = 0
        let itemId = try decodeVarint(from: payload, offset: &cursor)
        let result = try await handler.delete(itemId: itemId)
        return Data(encodeResultOk(result, encoder: { encodeI32($0.error) }))
    }

    private func dispatchrename(payload: Data) async throws -> Data {
        var cursor = 0
        let itemId = try decodeVarint(from: payload, offset: &cursor)
        let newParentId = try decodeVarint(from: payload, offset: &cursor)
        let newName = try decodeString(from: payload, offset: &cursor)
        let result = try await handler.rename(itemId: itemId, newParentId: newParentId, newName: newName)
        return Data(encodeResultOk(result, encoder: { encodeI32($0.error) }))
    }

    private func dispatchsetAttributes(payload: Data) async throws -> Data {
        var cursor = 0
        let itemId = try decodeVarint(from: payload, offset: &cursor)
        let _params_mode = try decodeOption(from: payload, offset: &cursor, decoder: { data, off in try decodeU32(from: data, offset: &off) })
        let _params_modifiedTime = try decodeOption(from: payload, offset: &cursor, decoder: { data, off in try decodeVarint(from: data, offset: &off) })
        let params = SetAttributesParams(mode: _params_mode, modifiedTime: _params_modifiedTime)
        let result = try await handler.setAttributes(itemId: itemId, params: params)
        return Data(encodeResultOk(result, encoder: { encodeI32($0.error) }))
    }

    private func dispatchping(payload: Data) async throws -> Data {
        // No arguments to decode
        let result = try await handler.ping()
        return Data(encodeResultOk(result, encoder: { encodeString($0) }))
    }
}

public final class VfsStreamingDispatcher {
    private let handler: VfsHandler
    private let registry: IncomingChannelRegistry
    private let taskSender: TaskSender

    public init(handler: VfsHandler, registry: IncomingChannelRegistry, taskSender: @escaping TaskSender) {
        self.handler = handler
        self.registry = registry
        self.taskSender = taskSender
    }

    public func dispatch(methodId: UInt64, requestId: UInt64, payload: Data) async {
        switch methodId {
        case 0xac1f4b76a434caf5:
            await dispatchlookup(requestId: requestId, payload: payload)
        case 0xc968b68989c3f020:
            await dispatchgetAttributes(requestId: requestId, payload: payload)
        case 0x075923273ab49e29:
            await dispatchreadDir(requestId: requestId, payload: payload)
        case 0x9c80fd555999d0e1:
            await dispatchread(requestId: requestId, payload: payload)
        case 0x5d398e81123c3597:
            await dispatchwrite(requestId: requestId, payload: payload)
        case 0x2caaf8adf5eda0e1:
            await dispatchcreate(requestId: requestId, payload: payload)
        case 0xfa37cb27061e7e2a:
            await dispatchdelete(requestId: requestId, payload: payload)
        case 0x4d68b4b3208a8c07:
            await dispatchrename(requestId: requestId, payload: payload)
        case 0x5dcd5793362fcd20:
            await dispatchsetAttributes(requestId: requestId, payload: payload)
        case 0xe35cdfdca59ce5ab:
            await dispatchping(requestId: requestId, payload: payload)
        default:
            taskSender(.response(requestId: requestId, payload: encodeUnknownMethodError()))
        }
    }

    /// Pre-register channel IDs from a request payload.
    /// Call this synchronously before spawning the dispatch task to avoid
    /// race conditions where Data arrives before channels are registered.
    public static func preregisterChannels(methodId: UInt64, payload: Data, registry: ChannelRegistry) async {
        switch methodId {
        default:
            break
        }
    }

    private func dispatchlookup(requestId: UInt64, payload: Data) async {
        do {
            var cursor = 0
            let parentId = try decodeVarint(from: payload, offset: &cursor)
            let name = try decodeString(from: payload, offset: &cursor)
            let result = try await handler.lookup(parentId: parentId, name: name)
            taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeVarint($0.itemId) + { v in
    switch v {
    case .file:
        return [UInt8(0)]
    case .directory:
        return [UInt8(1)]
    case .symlink:
        return [UInt8(2)]
    }
}($0.itemType) + encodeI32($0.error) })))
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError()))
        }
    }

    private func dispatchgetAttributes(requestId: UInt64, payload: Data) async {
        do {
            var cursor = 0
            let itemId = try decodeVarint(from: payload, offset: &cursor)
            let result = try await handler.getAttributes(itemId: itemId)
            taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeVarint($0.attrs.itemId) + { v in
    switch v {
    case .file:
        return [UInt8(0)]
    case .directory:
        return [UInt8(1)]
    case .symlink:
        return [UInt8(2)]
    }
}($0.attrs.itemType) + encodeVarint($0.attrs.size) + encodeVarint($0.attrs.modifiedTime) + encodeVarint($0.attrs.createdTime) + encodeU32($0.attrs.mode) + encodeI32($0.error) })))
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError()))
        }
    }

    private func dispatchreadDir(requestId: UInt64, payload: Data) async {
        do {
            var cursor_ = 0
            let itemId = try decodeVarint(from: payload, offset: &cursor_)
            let cursor = try decodeVarint(from: payload, offset: &cursor_)
            let result = try await handler.readDir(itemId: itemId, cursor: cursor)
            taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeVec($0.entries, encoder: { encodeString($0.name) + encodeVarint($0.itemId) + { v in
    switch v {
    case .file:
        return [UInt8(0)]
    case .directory:
        return [UInt8(1)]
    case .symlink:
        return [UInt8(2)]
    }
}($0.itemType) }) + encodeVarint($0.nextCursor) + encodeI32($0.error) })))
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError()))
        }
    }

    private func dispatchread(requestId: UInt64, payload: Data) async {
        do {
            var cursor = 0
            let itemId = try decodeVarint(from: payload, offset: &cursor)
            let offset = try decodeVarint(from: payload, offset: &cursor)
            let len = try decodeVarint(from: payload, offset: &cursor)
            let result = try await handler.read(itemId: itemId, offset: offset, len: len)
            taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeBytes(Array($0.data)) + encodeI32($0.error) })))
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError()))
        }
    }

    private func dispatchwrite(requestId: UInt64, payload: Data) async {
        do {
            var cursor = 0
            let itemId = try decodeVarint(from: payload, offset: &cursor)
            let offset = try decodeVarint(from: payload, offset: &cursor)
            let data = try decodeBytes(from: payload, offset: &cursor)
            let result = try await handler.write(itemId: itemId, offset: offset, data: data)
            taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeVarint($0.bytesWritten) + encodeI32($0.error) })))
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError()))
        }
    }

    private func dispatchcreate(requestId: UInt64, payload: Data) async {
        do {
            var cursor = 0
            let parentId = try decodeVarint(from: payload, offset: &cursor)
            let name = try decodeString(from: payload, offset: &cursor)
            let _itemType_disc = try decodeU8(from: payload, offset: &cursor)
            let itemType: ItemType
            switch _itemType_disc {
            case 0:
                itemType = .file
            case 1:
                itemType = .directory
            case 2:
                itemType = .symlink
            default:
                throw RoamError.decodeError("unknown enum variant")
            }
            let result = try await handler.create(parentId: parentId, name: name, itemType: itemType)
            taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeVarint($0.itemId) + encodeI32($0.error) })))
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError()))
        }
    }

    private func dispatchdelete(requestId: UInt64, payload: Data) async {
        do {
            var cursor = 0
            let itemId = try decodeVarint(from: payload, offset: &cursor)
            let result = try await handler.delete(itemId: itemId)
            taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeI32($0.error) })))
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError()))
        }
    }

    private func dispatchrename(requestId: UInt64, payload: Data) async {
        do {
            var cursor = 0
            let itemId = try decodeVarint(from: payload, offset: &cursor)
            let newParentId = try decodeVarint(from: payload, offset: &cursor)
            let newName = try decodeString(from: payload, offset: &cursor)
            let result = try await handler.rename(itemId: itemId, newParentId: newParentId, newName: newName)
            taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeI32($0.error) })))
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError()))
        }
    }

    private func dispatchsetAttributes(requestId: UInt64, payload: Data) async {
        do {
            var cursor = 0
            let itemId = try decodeVarint(from: payload, offset: &cursor)
            let _params_mode = try decodeOption(from: payload, offset: &cursor, decoder: { data, off in try decodeU32(from: data, offset: &off) })
            let _params_modifiedTime = try decodeOption(from: payload, offset: &cursor, decoder: { data, off in try decodeVarint(from: data, offset: &off) })
            let params = SetAttributesParams(mode: _params_mode, modifiedTime: _params_modifiedTime)
            let result = try await handler.setAttributes(itemId: itemId, params: params)
            taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeI32($0.error) })))
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError()))
        }
    }

    private func dispatchping(requestId: UInt64, payload: Data) async {
        do {
            var cursor = 0
            let result = try await handler.ping()
            taskSender(.response(requestId: requestId, payload: encodeResultOk(result, encoder: { encodeString($0) })))
        } catch {
            taskSender(.response(requestId: requestId, payload: encodeInvalidPayloadError()))
        }
    }

}

