name: FsKitty
options:
  bundleIdPrefix: me.amos
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "26.0"
    DEVELOPMENT_TEAM: B2N6FSRTPV
    CODE_SIGN_STYLE: Automatic

packages:
  rapace-swift:
    url: https://github.com/bearcove/rapace-swift
    branch: main

targets:
  FsKitty:
    type: application
    platform: macOS
    sources:
      - path: FsKitty
        excludes:
          - "*.entitlements"
          - Info.plist
    entitlements:
      path: FsKitty/FsKitty.entitlements
      properties:
        com.apple.security.app-sandbox: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.amos.fs-kitty
        INFOPLIST_FILE: FsKitty/Info.plist
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: FsKittyExt
        embed: true
        codeSign: true

  FsKittyExt:
    type: extensionkit-extension
    platform: macOS
    sources:
      - path: FsKittyExt
        excludes:
          - "*.entitlements"
          - Info.plist
    entitlements:
      path: FsKittyExt/FsKittyExt.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
        com.apple.developer.fskit.fsmodule: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.amos.fs-kitty.ext
        PRODUCT_NAME: fs-kitty
        INFOPLIST_FILE: FsKittyExt/Info.plist
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: rapace-swift
        product: Rapace
      - package: rapace-swift
        product: Postcard
