name: FsKitty
options:
  bundleIdPrefix: me.amos
  deploymentTarget:
    macOS: "15.4"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "15.4"
    DEVELOPMENT_TEAM: B2N6FSRTPV
    CODE_SIGN_STYLE: Automatic

targets:
  FsKitty:
    type: application
    platform: macOS
    sources:
      - path: FsKitty
        excludes:
          - "*.entitlements"
          - Info.plist
    entitlements:
      path: FsKitty/FsKitty.entitlements
      properties:
        com.apple.security.app-sandbox: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.amos.fs-kitty
        INFOPLIST_FILE: FsKitty/Info.plist
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: FsKittyExt
        embed: true
        codeSign: true

  FsKittyExt:
    type: extensionkit-extension
    platform: macOS
    sources:
      - path: FsKittyExt
        excludes:
          - "*.entitlements"
          - BridgeHeaders
          - Info.plist
    entitlements:
      path: FsKittyExt/FsKittyExt.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
        com.apple.developer.fskit.fsmodule: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: me.amos.fs-kitty.ext
        PRODUCT_NAME: fs-kitty
        INFOPLIST_FILE: FsKittyExt/Info.plist
        GENERATE_INFOPLIST_FILE: false
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        # Swift settings
        SWIFT_OBJC_BRIDGING_HEADER: ""
        SWIFT_INCLUDE_PATHS: "$(SRCROOT)/FsKittyExt/BridgeHeaders"
        # Header search paths for swift-bridge generated headers
        HEADER_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/FsKittyExt/BridgeHeaders"
        # Link to Rust static library
        LIBRARY_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/../target/release"
        OTHER_LDFLAGS:
          - "-lfs_kitty_swift"
        # Required for C interop
        CLANG_ENABLE_MODULES: true
